### ISSUE TITLE
可以用Alt+拖动窗口标题栏来排列吗？

### ISSUE THREAD

**Issue by Baiyssy** [mirtlecn/GridMove#1]
拖动整个窗口会和程序本身的操作冲突

谢谢！

**Comment by mirtlecn** [comment]
一些没有用标准窗口框架的应用，例如 Firefox，Affinity 套件，利用此工具拖动所谓「标题栏」时，会出现和程序本身功能冲突的情况。

比如 Affinity 套件菜单闪烁无法调整，Firefox 的标题栏会出现一次然后消失。

Alt 键确实在某些应用有特殊作用，所以应用现在已经改成了 win 键拖动整个窗口，目前没有发现问题。

暂时应该不会启用拖动标题栏的功能。
