### ISSUE TITLE
Recognized as a tojan by Windows Security

### ISSUE THREAD

**Issue by jxai** [mirtlecn/GridMove#6]
After installation, Windows Security immediately reported that it found "Trojan:Script/Phonzy.B!ml" in GridMove.exe, deemed it as a Severe thread and quarantined the file.

What could be the cause and how to resolve it?

**Comment by mirtlecn** [comment]
I'm not a computer security expert, so I'm not sure how security software determines if a program is a virus.

there are all the source code and compile scripts for GridMove. The AHK language it uses is also open source and available for auditing. All I can say is that, according to its design, the program only does what it's supposed to do.

P.S. you can try version 2.01 of GridMove, which has been released for a long time and hasn't been reported as being flagged as a trojan

P.P.S. Based on the experience of other open-source software, getting flagged as malware is not uncommon. Purchasing a paid software certificate and manually submitting the software to security software for review and whitelisting often resolves the issue.
